theme: jekyll-theme-minimal
title: codergrl.github.io
description: Welcome to my GitHub site. This page summarizes all the public projects I have contributed to, and describes my level of involvement. 
